config/routes.rb
MiacMednet::Application.routes.draw do

  root :to => 'main#index'
  get 'main' => 'main#index'
  get 'about' => 'main#about'
  resources :main

  devise_for :users

  resources :users, :only => :index do
    member do
      get 'profile'
      post 'profile'
    end
    collection do
      get 'manage'
      get 'adduser'
      post 'adduser'
    end
  end

  resources :videos, :only => :index do
	  member do
		  get 'cast'
	  end
  end

  resources :phonebook, :only => :index do
    member do
      get 'contact'
    end
  end

  resources :contacts, :only => :index

  resources :articles, :only => :index do
    collection do
      get 'instruction'
      get 'helpful'
      get 'archive'
      get 'documents'
      get 'videotuts'
      get 'add'
      get 'addvideo'
      get 'manage'
      post 'manage'
    end
    member do
      get 'edit'
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def index
		@videos = Article.paginate(:page => params[:page], :per_page => 20).types_5
	end
	def cast
		@cast = Article.find(params[:id])
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/cast.haml
%center
	%div.col-lg-12
		%div#info
			%h1 #{@cast.title.html_safe}
			%p #{@cast.body.html_safe}
		%div#video
			%iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :src => "http://www.youtube.com/embed/#{@cast.vid_url}", :width => "853"}

app/views/videos/index.haml
#content-top
	#content-top-inner
		.container
			.row
				.span12
					%h1 Видеокурсы
					%ul.breadcrumb
						%li
							= link_to articles_path, class: (request.path == root_path ? "selected" : " ") do
								Статьи
							%span.divider /
						%li.active Видеокурсы
%section#content
	.container
		.row
			.span12
				= render 'articles/info_nav'
				-if @videos.blank?
					%h3
						= I18n.t :oops_no_data_or_db_connection
				- else
					%div.col-lg-12
						%ul.list-unstyled.video-list-thumbs.row
							- @videos.each do |video|
								%li.col-lg-3.col-sm-4.col-xs-6
									= link_to cast_video_path(id: video.id) do
										.img-responsive
											= image_tag("video_thumb_default.png", style: "width:100%", alt: "Обложка видео")
										%h2
											=video.title
										%span.glyphicon.glyphicon-play-circle


				#pagination
					= will_paginate @videos