config/routes.rb
MiacMednet::Application.routes.draw do

  root :to => 'main#index'
  get 'main' => 'main#index'
  get 'about' => 'main#about'
  resources :main

  devise_for :users

  resources :users, :only => :index do
    member do
      get 'profile'
      post 'profile'
    end
    collection do
      get 'manage'
      get 'adduser'
      post 'adduser'
    end
  end

  resources :videos, :only => :index do
	  member do
		  get 'cast'
	  end
  end

  resources :phonebook, :only => :index do
    member do
      get 'contact'
    end
  end

  resources :contacts, :only => :index

  resources :articles, :only => :index do
    collection do
      get 'instruction'
      get 'helpful'
      get 'archive'
      get 'documents'
      get 'videotuts'
      get 'add'
      get 'addvideo'
      get 'manage'
      post 'manage'
    end
    member do
      get 'edit'
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    if user.role? :Администратор
      can :manage, :all
    elsif user.role? :Модератор
      can :manage, Article do |article|
        article.try(:owner) == user
      end
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :title, :preview, :body, :published_at, :published_to, :user_id, :types, :vid_url
	scope :types_0,  where(types: 0)
	scope :types_1,  where(types: 1)
	scope :types_2,  where(types: 2)
	scope :types_3,  where(types: 3)
	scope :types_4,  where(types: 4)
	scope :types_5,  where(types: 5)

	TYPES = {123 => {name: "Тип (Выберите...)"}, 1 => {name: "Полезная информация"}, 2 => {name: "Инструкции"}, 3 => {name: "Документы"}, 4 => {name: "Файловый архив"}, 5 => {name: "Видеокурсы"}, 6 => {name: "ДЛО"}}

	def self.add_article params,current_user
		Article.create(title:params[:title], types:params[:types], preview:params[:preview], body:params[:body], vid_url: (params[:vid_url] if params[:vid_url].present?), published_at: Time.now, published_to: Time.now,user_id: current_user)
	end

	def self.edit_article params
		Article.find(params[:id]) if Article.find(params[:id]).present?

	end
	def self.remove_article params
		Article.find(params[:id]).delete if Article.find(params[:id]).present?
	end

	def self.update_article params
		if Article.find(params[:id]).present?
			Article.find(params[:id]).update_attributes(title: params[:title],preview:params[:preview],body: params[:body])
		end
	end

	def self.aaaa params
		if params[:search].present?
			key = "%#{params[:search]}%"
			Article.where('body LIKE :search OR preview LIKE :search OR title LIKE :search', search: key).order(:title)
		else
			Article.all
		end
	end
end

app/models/block.rb
class Block < ActiveRecord::Base
attr_accessible :user_id, :reason, :blocked_at, :unblocked_at
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :map_id,:lsd_ids,:name,:district
  has_one :map_data, :dependent => :destroy
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :desc, :name, :phone
end

app/models/info_desk.rb
class InfoDesk < ActiveRecord::Base
  attr_accessible :contact_email, :contact_tel, :position, :private_email, :private_tel, :user_id, :organization_id, :department_id, :created_at, :updated_at
end

app/models/map_data.rb
class MapData < ActiveRecord::Base
  attr_accessible :city_id, :date, :primary_dr_ticket, :secondary_dr_ticket
  # db_magic :connection => :slave
  # MapData.table_name = "clients"
  belongs_to :city
  scope :today, where("date between ? and ?",Date.today.beginning_of_day, Date.today.end_of_day)
  scope :yesterday, where("date between ? and ?",Date.today.beginning_of_day-1.day, Date.today.end_of_day-1.day)
end

app/models/message.rb
class Message < MailForm::Base
	attribute :name,          :validate => true
	attribute :email,         :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :subject,       :validate => true
	attribute :message,       :validate => true

	def headers
		{
				:subject => "Связь с mednet",
				:to => "lekufowo@lackmail.net",
				:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :address, :city_id, :description, :logo, :name, :tel_secretary, :fax, :city_code
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name
  has_and_belongs_to_many :users

  # ROLES = {1 => {name: "Полезная информация"}, 2 => {name: "Инструкции"}, 3 => {name: "Документы"}, 4 => {name: "Файловый архив"}, 5 => {name: "Видеокурсы"}, 6 => {name: "ДЛО"}}
  def RoleOutput
    "#{name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_and_belongs_to_many :roles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :username, :password, :parent_id, :ansestry, :fio, :moderator, :admin, :hospital, :blocks, :remember_me, :encrypted_password, :created_at, :sign_in_count, :updated_at, :role_id
  has_ancestry
	# before_save :setup_role


	def role?(role)
		return !!self.roles.find_by_name(role.to_s.camelize)
	end

	# Default role is "Registered"
	# def setup_role
	# 	if self.role_ids.empty?
	# 		self.role_ids = [4]
	# 	end
	# end

	def self.change_fio params, current_user
		current_user.update_attributes(fio: params[:fio])
	end

  def self.change_password params, current_user
	  current_user.update_attributes(password: params[:new_password], sign_in_count: User.find(current_user.id).sign_in_count+1) if User.find(current_user.id).password.present?
  end

	def self.blocked_user params
		User.find(params[:id]).update_attributes(blocks: true) if User.find(params[:id]).present?
		Block.create(user_id:params[:id], reason:"no reason", blocked_at:Time.now) if Block.where(user_id: params[:id],reason:"no reason", blocked_at: Time.now).present?
	end

  def self.unblocked_user params
	  User.find(params[:id]).update_attributes(blocks: false) if User.find(params[:id]).present?
		Block.where(user_id: params[:id], unblocked_at: nil).first.update_attributes(unblocked_at:Time.now) if Block.where(user_id: params[:id], unblocked_at: nil).first.present?
  end

	def self.add_user params
		User.create(email: params[:email], username: params[:username], password:"123456aA", fio:params[:fio], role_id:params[:role_id], created_at:Time.now, sign_in_count:0, updated_at:Time.now)
	end
end

app/models/user_ability.rb
class UserAbility
  include CanCan::Ability
  def initialize(user)
    user ||= User.new # guest user
    if user.role? :Администратор
      can :manage, :all
    elsif user.role? :Модератор
      can :manage, Article do |article|
        article.try(:owner) == user
      end
    else
      can :read, :all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_name_id(name_id)
		case name_id
			when 1 then name = "Полезная информация"
			when 2 then name = "Инструкции"
			when 3 then name = "Документы"
			when 4 then name = "Файловый архив"
			when 5 then name = "Видеокурсы"
			when 6 then name = "ДЛО"
		end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/phonebook_helper.rb
module PhonebookHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_old_application.html.haml
!!!
%html{:lang => "ru"}
	%head
		%meta{:charset => "utf-8"}
		%meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
		%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
		%meta{:content => "", :name => "description"}/
		%meta{:content => "", :name => "author"}/
		%title= content_for?(:title) ? yield(:title) : "Mednet"

		= csrf_meta_tags
		/ Le HTML5 shim, for IE6-8 support of HTML elements
		/[if lt IE 9]
			= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

		= stylesheet_link_tag "application", :media => "all"
		= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

		= javascript_include_tag "application"

		-#= javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js'


		%body
			= render 'shared/topbar'

			.col-lg-12{style: "margin-top: 1%;"}
				= bootstrap_flash
				= yield

app/views/layouts/application.html.haml
!!!
%html.no-js{:lang => "ru"}
	%head
		%meta{:charset => "utf-8"}/
		%meta{:content => "company,services,responsive,subscribe,business,marketing,corporate,ipad,iphone,site template", :name => "keywords"}/
		%title Mednet
		%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/

		%link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700", :rel => "stylesheet", :type => "text/css"}/

		= csrf_meta_tags

		= stylesheet_link_tag "application", :media => "all"
		= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

		= javascript_include_tag "application"

	%body

		= render "shared/topbar"

		.span12
			.container
				%center
					= bootstrap_flash
		.row
			= yield
		= render "shared/ulala" if request.path == root_path
		= render "shared/footer"

app/views/shared/_footer.haml
%footer#footer
	.container
		.row
			/ first column starts
			.span9
				/ row for nested columns starts
				.row
					/ first nested column starts
					.span3
						%h5 About Megabiz
						%p Megabiz at vero eros et accumsan odio dignissim blandit praesent luptatum dolor sit maet ipsum lorem delenit. Nam liber tempor cum soluta legentis nobis.
					/ second nested column starts
					.span3
						%h5 Latest Tweets
						#twitter
						%a.tweet-birdy{:href => "#"} Follow us
					/ third nested column starts
					.span3
						%h5 Some Links
						%ul.list-arrow
							%li
								%a{:href => "#"} Careers
							%li
								%a{:href => "#"} Press Release
							%li
								%a{:href => "#"} Forum
							%li
								%a{:href => "#"} Annual Report
				/ row for nested columns ends
				/ divider here
				.divider-dark
				%p.pull-left
					= image_tag("footer-logo.png", :style => "margin-right: 10px;", :alt => "footer-logo", )
					© Copyright 2013 by Tansh. All Rights Reserved.
				%ul.copyright.inline-right
					%li
						%a{:href => "#"} Support
					%li
						%a{:href => "#"} Privacy Policy
					%li
						%a{:href => "#"} Impressum
			/ first column ends
			/ second column starts
			.span3.pos-rel
				/ box-dark starts
				.box-dark
					= image_tag("preview/footer-map.png")
					.spacer-20px
					%address
						Megabizz Inc.
						%br/
						32 East Creek Blvd, Lorem County
						%br/
						Suite 590, Bos Boomer,
						%br/
						IN 20076
					%a.mybtn{:href => "#"} Contact us

app/views/shared/_old__sidebar.haml
#sidebar.navbar-default.sidebar{:role => "navigation"}
	.sidebar-nav.navbar-collapse
		%ul#side-menu.nav
			%li
				%a.active{:href => "index.html"}
					%i.fa.fa-dashboard.fa-fw
					Панель
			%li
				%a{:href => "#"}
					%i.fa.fa-bar-chart-o.fa-fw
					Графики
					%span.fa.arrow
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} Графики
				/ /.nav-second-level
			%li
				%a{:href => "#"}
					%i.fa.fa-table.fa-fw
					Таблицы
			%li
				%a{:href => "#"}
					%i.fa.fa-edit.fa-fw
					Формы
			%li
				%a{:href => "#"}
					%i.fa.fa-wrench.fa-fw
					Настройки
					%span.fa.arrow
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} Оповещения
					%li
						%a{:href => "#"} Сообщения
					%li
						%a{:href => "#"} Пользователи
					%li
						%a{:href => "#"} Группы
					%li
						%a{:href => "#"}
							Глобальные
							%span#ttip-config-changed.badge.alert-warning !
				/ /.nav-second-level
			%li
				%a{:href => "#"}
					%i.fa.fa-sitemap.fa-fw
					Просто меню
					%span.fa.arrow
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} пуф
					%li
						%a{:href => "#"} тык
					%li
						%a{:href => "#"}
							подменю
							%span.fa.arrow
						%ul.nav.nav-third-level
							%li
								%a{:href => "#"} бдыщ
						/ /.nav-third-level
				/ /.nav-second-level
			%li
				%a{:href => "#"}
					%i.fa.fa-external-link.fa-fw
					Ссылки
					%span.fa.arrow
					%span#ttip-external-links.badge.alert-success
						%i.fa.fa-info
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} Яндекс
					%li
						%a{:href => "#"} Гугл

app/views/shared/_old__topbar.haml
%nav.navbar.navbar-blue.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
	.navbar-header
		%ul#afterHeader.nav.navbar-top-links.navbar-right
			%li
		%button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
			%span.sr-only Навигация
			%span.icon-bar
			%span.icon-bar
			%span.icon-bar
		%span.navbar-brand	
			= link_to image_tag('mednet.png', style: 'width:50%; margin-top: -15px;'), root_path
		

	%ul.nav.navbar-nav.navbar-right
		%li
			= link_to " ", "#", style: "color:white; font-size: 40px;"
		%li
			= link_to root_path do
				%i.fa.fa-home
				Главная
		%li
			= link_to articles_path do
				%i.fa.fa-newspaper-o
				Новости
		%li
			= link_to root_path do
				%i.fa.fa-phone
				Телефонный справочник
		%li.dropdown
			= link_to "#",class:"dropdown-toggle","data-toggle" => "dropdown", :href => "#" do
				%i.fa.fa-file-text-o
				Полезные материалы
				%i.fa.fa-caret-down
			%ul.dropdown-menu.dropdown-user.dropdown-menu-right
				%li
					= link_to helpful_articles_path do
						Полезные материалы
				%li.divider
				%li.dropdown-header
					Разделы
				%li
					= link_to instruction_articles_path do
						Инструкции
				%li
					= link_to documents_articles_path do
						Оф. Документы
				%li
					= link_to archive_articles_path do
						Файловый архив
				%li
					= link_to videotuts_articles_path do
						Видеокурсы

			:javascript
				window.onload = function(){
						(function(){
								var date = new Date();
								var time = date.getHours()+':'+(date.getMinutes()<10?'0':'') + date.getMinutes();
								
								document.getElementsByTagName('a')[1].innerHTML = time;
								window.setTimeout(arguments.callee, 1000);
						})();
				};
				
		- if user_signed_in?
			%li.dropdown
				= link_to "#",class:"dropdown-toggle","data-toggle" => "dropdown", :href => "#" do
					%i.fa.fa-user.fa-fw
					%i.fa.fa-caret-down
				%ul.dropdown-menu.dropdown-user.dropdown-menu-right
					%li
						= link_to profile_user_path(current_user.id) do
							%i.fa.fa-user.fa-fw
							Мой профиль
					%li
						%a{:href => "#"}
							%i.fa.fa-gear.fa-fw
							Настройки
					%li.divider
					- if current_user.admin == true
						%li.dropdown-header
							Административные разделы
						%li
							%a{:href => manage_articles_path}
								%i.fa.fa-gear.fa-fw
								Управление статьями
						%li.divider
					%li
						= link_to destroy_user_session_path, :method => :delete, :data => { :confirm => 'Вы уверены, что хотите выйти из системы?' } do
							%i.fa.fa-sign-out.fa-fw
							Выйти
		- else
			%li.dropdown{:style => "cursor: pointer"}
				= link_to "Вход", :class => "dropdown-toggle", "data-toggle" => "dropdown" do
					%i.fa.fa-user.fa-fw
					%b.caret
				.dropdown-menu{style: "width:260px;"}
					%center
						%h4
							Авторизация
						= form_tag new_user_session_path, :class => "minilogin", :style => "width: 65%;" do
							%br
							= text_field_tag 'user[username]', nil,{:class => "input-medium", placeholder: "логин", :autofocus => true}
							= password_field_tag 'user[password]', nil,{:class => "input-medium", placeholder: "Пароль"}
							%label.checkbox
								= check_box_tag 'user[remember_me]'
								Запомнить меня
							= submit_tag "Войти", class: 'btn btn-mini btn-success', style: "margin-top: -2px;"
			
		%li
			= link_to "#", type: "submit" do
				%i.fa.fa-search

app/views/shared/_page-header.haml
#content-top
	#content-top-inner
		.container
			.row
				.span12

app/views/shared/_sidebar.haml
#sidebar.navbar-default.sidebar{:role => "navigation"}
	.sidebar-nav.navbar-collapse
		%ul#side-menu.nav
			%li
				%a.active{:href => "index.html"}
					%i.fa.fa-dashboard.fa-fw
					Панель
			%li
				%a{:href => "#"}
					%i.fa.fa-bar-chart-o.fa-fw
					Графики
					%span.fa.arrow
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} Графики
				/ /.nav-second-level
			%li
				%a{:href => "#"}
					%i.fa.fa-table.fa-fw
					Таблицы
			%li
				%a{:href => "#"}
					%i.fa.fa-edit.fa-fw
					Формы
			%li
				%a{:href => "#"}
					%i.fa.fa-wrench.fa-fw
					Настройки
					%span.fa.arrow
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} Оповещения
					%li
						%a{:href => "#"} Сообщения
					%li
						%a{:href => "#"} Пользователи
					%li
						%a{:href => "#"} Группы
					%li
						%a{:href => "#"}
							Глобальные
							%span#ttip-config-changed.badge.alert-warning !
				/ /.nav-second-level
			%li
				%a{:href => "#"}
					%i.fa.fa-sitemap.fa-fw
					Просто меню
					%span.fa.arrow
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} пуф
					%li
						%a{:href => "#"} тык
					%li
						%a{:href => "#"}
							подменю
							%span.fa.arrow
						%ul.nav.nav-third-level
							%li
								%a{:href => "#"} бдыщ
						/ /.nav-third-level
				/ /.nav-second-level
			%li
				%a{:href => "#"}
					%i.fa.fa-external-link.fa-fw
					Ссылки
					%span.fa.arrow
					%span#ttip-external-links.badge.alert-success
						%i.fa.fa-info
				%ul.nav.nav-second-level
					%li
						%a{:href => "#"} Яндекс
					%li
						%a{:href => "#"} Гугл

app/views/shared/_topbar.haml
%section#header

	.container.clearfix
		.row
			.span4.pos-rel
				= link_to image_tag("mednet.png",style:"width: 210px;", alt: "logo"), root_path
				.logo-info
			.span8
				%ul.social
					%li.pos-rel
						.search-header
							%form.searchform{:action => ".", :method => "get"}
								%input{:name => "s", :placeholder => "", :type => "text"}
				.clearfix
			.span12
				.menu-wrapper
					#smoothmenu.ddsmoothmenu
						%ul
							%li
								-#%a.{:href => "index.html"} Home
								= link_to root_path, class: (request.path == root_path ? "selected" : " ") do
									%i.fa.fa-home
							%li
								= link_to articles_path do
									%i.fa.fa-newspaper-o
									Новости
							%li
								= link_to phonebook_index_path do
									%i.fa.fa-phone
									Cправочник
							%li
								= link_to helpful_articles_path do
									%i.fa.fa-file-text-o
									Полезные материалы
								%ul
									%li
										= link_to instruction_articles_path do
											Инструкции
									%li
										= link_to documents_articles_path do
											Оф. Документы
									%li
										= link_to archive_articles_path do
											Файловый архив
									%li
										= link_to videos_path do
											Видеокурсы
							%li
								= link_to contacts_path do
									%i.fa.fa-envelope
									Контакты
						%ul.inline-right
							%li#topdown
								= image_tag("icons/icon-phone.png")
								(+91) 123 456-7892
							%li
								%a
									%i.fa.fa-user
								- if user_signed_in?
									%ul
										%li
											= link_to profile_user_path(current_user.id) do
												%i.fa.fa-user.fa-fw
												Мой профиль
										%li
											= link_to manage_articles_path do
												%i.fa.fa-file-text-o.fa-fw
												Управление статьями
										%li
											= link_to manage_users_path do
												%i.fa.fa-users.fa-fw
												Управление пользователями
										%li
											= link_to destroy_user_session_path, :method => :delete, :data => { :confirm => 'Вы уверены, что хотите выйти из системы?' } do
												%i.fa.fa-sign-out.fa-fw
												Выйти
								- else
									%ul.dropdown-menu
										%center
											%h4
												Авторизация
											= form_tag new_user_session_path, id:"minilogin", :class => "minilogin", :style => "width: 65%;" do
												%br
												= text_field_tag 'user[username]', nil,{:class => "input-medium", placeholder: "логин", :autofocus => true}
												= password_field_tag 'user[password]', nil,{:class => "input-medium", placeholder: "Пароль"}
												%label.checkbox
													= check_box_tag 'user[remember_me]'
													Запомнить меня
												= submit_tag "Войти", class: 'btn btn-mini btn-success', style: "margin-top: -2px;"

					.clearfix
						-#:javascript
						-#	$(document).ready(function(){
						-#		$.validator.addMethod(
						-#			'regexp',
						-#			function(value, element, regexp) {
						-#				var re = new RegExp(regexp);
						-#				return this.optional(element) || re.test(value);
						-#			},
						-#			"Please check your input."
						-#		);
						-#	});
						-#	$(document).ready(function(){
						-#		$("#minilogin").validate({
						-#			lang: 'ru',
						-#			rules: {
						-#				'user[username]': {
						-#					minlength: 5,
						-#					required: true,
						-#				},
						-#				'user[password]': {
						-#					required: true
						-#				}
						-#			},
						-#			messages: {
						-#				'user[username]':{
						-#					regexp: 'Логин может состоять только из латинских букв и цифр.'
						-#				},
						-#				'user[password]': {
						-#					required: "Введите пароль."
						-#				}
						-#			},
						-#			highlight: function(element) {
						-#				$(element).closest('.control-group').removeClass('success').addClass('error');
						-#			},
						-#			success: function(element) {
						-#				element
						-#				.text('OK!').addClass('valid')
						-#				.closest('.control-group').removeClass('error').addClass('success');
						-#			}
						-#		});
						//	}); // end document.ready